// GENERATED by tools/build-data.mjs from data/sales.json when that file exists (else empty). Keys are unit ids, e.g. 'B1-5-07'.
// Values: { status?: 'available'|'reserved'|'sold'|'blocked', price?: number (UAH), ppm?: number (UAH per m²) }
export const SALES = {"updatedAt":null,"units":{}};
